# Generated by Django 6.0.4 on 2026-04-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('done', 'Done')], default='not_started', max_length=20)),
            ],
        ),
    ]
