# Generated by Django 6.0.4 on 2026-04-12 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_bank_info_received_client_business_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='bank_info_received',
        ),
        migrations.RemoveField(
            model_name='client',
            name='id_received',
        ),
        migrations.RemoveField(
            model_name='client',
            name='tax_documents_received',
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('business', 'Business')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='onboarding_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='onboarding_token',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='OnboardingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_full_name', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('business_number', models.CharField(blank=True, max_length=100)),
                ('service_needed', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='onboarding/id_docs/')),
                ('tax_document', models.FileField(blank=True, null=True, upload_to='onboarding/tax_docs/')),
                ('bank_document', models.FileField(blank=True, null=True, upload_to='onboarding/bank_docs/')),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='clients.client')),
            ],
        ),
    ]
