# Generated by Django 6.0.4 on 2026-04-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_client_bank_info_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
    ]
