# Generated by Django 6.0.4 on 2026-04-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingsubmission',
            name='annual_returns',
            field=models.FileField(blank=True, null=True, upload_to='onboarding/minute_book/annual_returns/'),
        ),
        migrations.AddField(
            model_name='onboardingsubmission',
            name='articles_of_incorporation',
            field=models.FileField(blank=True, null=True, upload_to='onboarding/minute_book/articles/'),
        ),
        migrations.AddField(
            model_name='onboardingsubmission',
            name='bylaws',
            field=models.FileField(blank=True, null=True, upload_to='onboarding/minute_book/bylaws/'),
        ),
        migrations.AddField(
            model_name='onboardingsubmission',
            name='cra_correspondence',
            field=models.FileField(blank=True, null=True, upload_to='onboarding/cra_docs/'),
        ),
        migrations.AddField(
            model_name='onboardingsubmission',
            name='directors_register',
            field=models.FileField(blank=True, null=True, upload_to='onboarding/minute_book/directors/'),
        ),
        migrations.AddField(
            model_name='onboardingsubmission',
            name='other_minute_book_file',
            field=models.FileField(blank=True, null=True, upload_to='onboarding/minute_book/other/'),
        ),
        migrations.AddField(
            model_name='onboardingsubmission',
            name='prior_financial_statements',
            field=models.FileField(blank=True, null=True, upload_to='onboarding/financials/'),
        ),
        migrations.AddField(
            model_name='onboardingsubmission',
            name='resolutions',
            field=models.FileField(blank=True, null=True, upload_to='onboarding/minute_book/resolutions/'),
        ),
        migrations.AddField(
            model_name='onboardingsubmission',
            name='share_certificates',
            field=models.FileField(blank=True, null=True, upload_to='onboarding/minute_book/share_certificates/'),
        ),
        migrations.AddField(
            model_name='onboardingsubmission',
            name='shareholder_register',
            field=models.FileField(blank=True, null=True, upload_to='onboarding/minute_book/shareholders/'),
        ),
    ]
