# Generated by Django 6.0.4 on 2026-04-13 01:59

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_onboardingsubmission_annual_returns_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='onboardingsubmission',
            name='annual_returns',
        ),
        migrations.RemoveField(
            model_name='onboardingsubmission',
            name='articles_of_incorporation',
        ),
        migrations.RemoveField(
            model_name='onboardingsubmission',
            name='bylaws',
        ),
        migrations.RemoveField(
            model_name='onboardingsubmission',
            name='cra_correspondence',
        ),
        migrations.RemoveField(
            model_name='onboardingsubmission',
            name='directors_register',
        ),
        migrations.RemoveField(
            model_name='onboardingsubmission',
            name='other_minute_book_file',
        ),
        migrations.RemoveField(
            model_name='onboardingsubmission',
            name='prior_financial_statements',
        ),
        migrations.RemoveField(
            model_name='onboardingsubmission',
            name='resolutions',
        ),
        migrations.RemoveField(
            model_name='onboardingsubmission',
            name='share_certificates',
        ),
        migrations.RemoveField(
            model_name='onboardingsubmission',
            name='shareholder_register',
        ),
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='onboarding_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='onboardingsubmission',
            name='bank_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/bank/'),
        ),
        migrations.AlterField(
            model_name='onboardingsubmission',
            name='business_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='onboardingsubmission',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/id/'),
        ),
        migrations.AlterField(
            model_name='onboardingsubmission',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='onboardingsubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='onboardingsubmission',
            name='tax_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/tax/'),
        ),
    ]
