# Generated by Django 6.0.4 on 2026-04-13 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_rename_client_email_client_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='created_at',
        ),
    ]
