# Generated by Django 6.0.4 on 2026-04-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_remove_client_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='onboarding_token',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
