# Generated by Django 6.0.4 on 2026-04-13 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_client_onboarding_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinuteBookDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/minute_book/')),
                ('uploaded_by', models.CharField(choices=[('client', 'Client'), ('accountant', 'Accountant')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minute_book_documents', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('identity', 'Identity'), ('tax', 'Tax'), ('banking', 'Banking')], max_length=20)),
                ('document_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/additional/')),
                ('uploaded_by', models.CharField(choices=[('client', 'Client'), ('accountant', 'Accountant')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_documents', to='clients.client')),
            ],
        ),
    ]
