# Generated by Django 6.0.4 on 2026-04-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_minutebookdocument_onboardingdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingdocument',
            name='category',
            field=models.CharField(choices=[('identity', 'Identity'), ('tax', 'Tax'), ('banking', 'Banking'), ('other', 'Other Documents')], max_length=20),
        ),
    ]
