# Generated by Django 5.2 on 2026-04-23 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_userprofile_assigned_clients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementLetterRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('content_html', models.TextField()),
                ('version', models.CharField(default='v1', max_length=10)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('is_signed', models.BooleanField(default=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.corporatelead')),
            ],
        ),
    ]
