# Generated by Django 5.2 on 2026-05-04 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0024_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('annual_return', 'Annual Return'), ('quebec_declaration', 'Québec Enterprise Register Declaration'), ('agm', 'Annual General Meeting'), ('t2_filing', 'Corporate Tax Filing (T2)'), ('gst_hst_filing', 'GST/HST Return'), ('minute_book_update', 'Minute Book Update'), ('pic_filing', 'PIC Filing'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('auto_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_tasks', to='clients.client')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
