# Generated by Django 5.2 on 2026-06-10 22:12

import clients.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0029_staffinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutebookdocument',
            name='file',
            field=models.FileField(upload_to='documents/minute_book/', validators=[clients.models.validate_document_file]),
        ),
        migrations.AlterField(
            model_name='onboardingdocument',
            name='file',
            field=models.FileField(upload_to='documents/additional/', validators=[clients.models.validate_document_file]),
        ),
        migrations.AlterField(
            model_name='onboardingsubmission',
            name='bank_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/bank/', validators=[clients.models.validate_document_file]),
        ),
        migrations.AlterField(
            model_name='onboardingsubmission',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/id/', validators=[clients.models.validate_document_file]),
        ),
        migrations.AlterField(
            model_name='onboardingsubmission',
            name='tax_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/tax/', validators=[clients.models.validate_document_file]),
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Yes/No'), ('select', 'Dropdown'), ('textarea', 'Long Text')], default='text', max_length=20)),
                ('options', models.TextField(blank=True, help_text='For dropdown: comma-separated options')),
                ('section', models.CharField(default='general', help_text='Which section to display in (general, tax, compliance)', max_length=50)),
                ('is_searchable', models.BooleanField(default=False, help_text='Include in global search')),
                ('order', models.PositiveIntegerField(default=0)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='clients.firm')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('firm', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SavedChartView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('config', models.JSONField(default=dict, help_text='Chart layout configuration (positions, filters, styles)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_charts', to='clients.firm')),
                ('home_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_charts', to='clients.client')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('issuance', 'Issuance'), ('transfer', 'Transfer'), ('cancellation', 'Cancellation'), ('conversion', 'Conversion'), ('split', 'Split')], max_length=20)),
                ('share_class', models.CharField(default='Common', max_length=50)),
                ('num_shares', models.PositiveIntegerField()),
                ('price_per_share', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('transaction_date', models.DateField()),
                ('resolution_ref', models.CharField(blank=True, help_text='Reference to board resolution authorizing this', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_transactions', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shareholder_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='clients.shareholder')),
                ('shareholder_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='clients.shareholder')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('download', 'Downloaded'), ('sign', 'Signed'), ('login', 'Logged In'), ('invite', 'Invited'), ('payment', 'Payment'), ('status', 'Status Change'), ('export', 'Exported'), ('other', 'Other')], default='other', max_length=20)),
                ('target_type', models.CharField(blank=True, help_text='e.g. Client, Invoice, ComplianceTask', max_length=50)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_name', models.CharField(blank=True, help_text='Human-readable name of the target', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary extra data (changes, file names, etc.)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='clients.firm')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['firm', '-created_at'], name='clients_act_firm_id_b1b372_idx'), models.Index(fields=['user', '-created_at'], name='clients_act_user_id_88f8f6_idx'), models.Index(fields=['target_type', 'target_id'], name='clients_act_target__3d68e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomEntityStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#64748b', help_text='Hex color code for the status badge', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_statuses', to='clients.firm')),
            ],
            options={
                'verbose_name_plural': 'Custom entity statuses',
                'ordering': ['order', 'name'],
                'unique_together': {('firm', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='clients.client')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='clients.customfield')),
            ],
            options={
                'unique_together': {('field', 'client')},
            },
        ),
    ]
