# Generated by Django 5.2.15 on 2026-06-11 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0030_add_activity_log_and_custom_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['firm', 'status'], name='clients_cli_firm_id_ba9aed_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['onboarding_submitted_at'], name='clients_cli_onboard_c6ec11_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancetask',
            index=models.Index(fields=['client', 'status'], name='clients_com_client__439111_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancetask',
            index=models.Index(fields=['due_date'], name='clients_com_due_dat_923b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='corporateprofile',
            index=models.Index(fields=['jurisdiction'], name='clients_cor_jurisdi_812d84_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client', 'status'], name='clients_inv_client__5174db_idx'),
        ),
    ]
