# Generated by Django 5.2.15 on 2026-06-11 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0031_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('events', models.JSONField(default=list, help_text='List of event types to subscribe to')),
                ('secret', models.CharField(blank=True, help_text='Optional secret for HMAC signature verification', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='clients.firm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
