# Generated by Django 5.2.15 on 2026-06-11 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0033_add_signatures'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('resolution', 'Board Resolution'), ('agreement', 'Agreement'), ('consent', 'Consent'), ('notice', 'Notice'), ('other', 'Other')], default='resolution', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('content_html', models.TextField(help_text='HTML template. Use {{ client.name }}, {{ profile.jurisdiction }}, etc.')),
                ('is_global', models.BooleanField(default=False, help_text='Available to all firms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('firm', models.ForeignKey(blank=True, help_text='Firm-specific template. Leave blank for global templates.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='clients.firm')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
