# Generated by Django 5.2.15 on 2026-06-11 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0035_add_messaging'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('category', models.CharField(default='general', max_length=50)),
                ('jurisdiction', models.CharField(choices=[('all', 'All Jurisdictions'), ('federal', 'Federal (CBCA)'), ('ontario', 'Ontario (OBCA)'), ('bc', 'British Columbia (BCA)'), ('quebec', 'Quebec (LSAQ)'), ('alberta', 'Alberta (ABCA)')], default='all', max_length=20)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords for search matching', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AIQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('matched_kb_id', models.PositiveIntegerField(blank=True, null=True)),
                ('response', models.TextField()),
                ('helpful', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_queries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
