# Generated by Django 5.2.15 on 2026-06-11 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0036_add_ai_assistant'),
    ]

    operations = [
        migrations.CreateModel(
            name='UBORecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('jurisdiction_of_residence', models.CharField(blank=True, max_length=100)),
                ('ownership_percentage', models.DecimalField(decimal_places=2, help_text='e.g. 33.33 for 33.33%', max_digits=5)),
                ('control_type', models.CharField(choices=[('ownership', 'Direct Ownership'), ('indirect', 'Indirect Control'), ('both', 'Both')], default='ownership', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('last_verified_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubo_records', to='clients.client')),
            ],
            options={
                'ordering': ['-ownership_percentage'],
            },
        ),
    ]
