# Generated by Django 5.2.15 on 2026-06-11 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0037_add_ubo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Firm logo (PNG, max 500KB)', null=True, upload_to='branding/logos/')),
                ('primary_color', models.CharField(default='#2563eb', help_text='Hex color for buttons, links, accents', max_length=7)),
                ('accent_color', models.CharField(default='#7c3aed', help_text='Secondary accent color', max_length=7)),
                ('portal_title', models.CharField(blank=True, help_text='Custom portal title shown in browser tab', max_length=100)),
                ('custom_domain', models.CharField(blank=True, help_text='e.g. portal.youraccountingfirm.com', max_length=255)),
                ('custom_css', models.TextField(blank=True, help_text='Optional custom CSS overrides')),
                ('hide_mortacc_branding', models.BooleanField(default=False, help_text='Hide "Powered by Mortacc" from portal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('firm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='clients.firm')),
            ],
        ),
        migrations.CreateModel(
            name='FirmDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='clients.firm')),
            ],
        ),
        migrations.CreateModel(
            name='TOTPDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=64)),
                ('is_setup', models.BooleanField(default=False, help_text='User has completed setup with QR scan')),
                ('backup_codes', models.JSONField(default=list, help_text='List of hashed backup codes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totp_device', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
