# Generated by Django 5.2.15 on 2026-06-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0039_add_marketplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateprofile',
            name='jurisdiction',
            field=models.CharField(blank=True, choices=[('federal', 'Federal'), ('ontario', 'Ontario'), ('bc', 'British Columbia'), ('quebec', 'Quebec'), ('alberta', 'Alberta')], max_length=20),
        ),
    ]
