# Generated by Django 5.2.15 on 2026-06-12 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0041_add_chatgpt_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('amber', 'Amber'), ('red', 'Red'), ('purple', 'Purple'), ('gray', 'Gray')], default='blue', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_task_statuses', to='clients.firm')),
            ],
            options={
                'verbose_name_plural': 'Custom task statuses',
                'ordering': ['sort_order', 'label'],
                'unique_together': {('firm', 'label')},
            },
        ),
        migrations.AddField(
            model_name='compliancetask',
            name='custom_status',
            field=models.ForeignKey(blank=True, help_text='Optional firm-defined workflow status shown alongside the base status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='clients.customtaskstatus'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('officer', 'Officer'), ('power_of_attorney', 'Power of Attorney'), ('signing_authority', 'Signing Authority'), ('registered_agent', 'Registered Agent'), ('accountant', 'Accountant'), ('lawyer', 'Lawyer'), ('auditor', 'Auditor'), ('other', 'Other')], default='officer', max_length=30)),
                ('title', models.CharField(blank=True, help_text='e.g. President, CFO, Corporate Secretary', max_length=100)),
                ('granted_by', models.CharField(blank=True, help_text='Resolution or instrument granting the appointment', max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clients.client')),
            ],
            options={
                'ordering': ['role', 'person_name'],
                'indexes': [models.Index(fields=['client', 'role'], name='clients_app_client__4909a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='EntityRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiction', models.CharField(help_text='e.g. Ontario, Alberta, Delaware', max_length=100)),
                ('registration_type', models.CharField(choices=[('home', 'Home Jurisdiction'), ('extra_provincial', 'Extra-Provincial'), ('foreign', 'Foreign Qualification'), ('business_name', 'Business Name'), ('licence', 'Licence / Permit')], default='extra_provincial', max_length=30)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('agent_name', models.CharField(blank=True, help_text='Registered agent / attorney for service', max_length=255)),
                ('registered_date', models.DateField(blank=True, null=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('expired', 'Expired'), ('withdrawn', 'Withdrawn')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='clients.client')),
            ],
            options={
                'ordering': ['jurisdiction'],
                'indexes': [models.Index(fields=['client', 'status'], name='clients_ent_client__9aba24_idx'), models.Index(fields=['renewal_date'], name='clients_ent_renewal_9069b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=100)),
                ('residency', models.CharField(blank=True, help_text='Jurisdiction of residence', max_length=100)),
                ('kyc_status', models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('verified', 'Verified'), ('expired', 'Expired')], default='not_started', max_length=20)),
                ('kyc_verified_date', models.DateField(blank=True, null=True)),
                ('id_type', models.CharField(blank=True, choices=[('passport', 'Passport'), ('drivers_licence', "Driver's Licence"), ('provincial_id', 'Provincial ID'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='clients.firm')),
            ],
            options={
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['firm', 'kyc_status'], name='clients_per_firm_id_7c8809_idx')],
                'unique_together': {('firm', 'full_name')},
            },
        ),
        migrations.CreateModel(
            name='ShareClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Common, Class A Preferred', max_length=100)),
                ('class_type', models.CharField(choices=[('common', 'Common'), ('preferred', 'Preferred'), ('special', 'Special')], default='common', max_length=20)),
                ('voting', models.BooleanField(default=True)),
                ('votes_per_share', models.PositiveIntegerField(default=1)),
                ('authorized_shares', models.PositiveBigIntegerField(blank=True, help_text='Blank = unlimited', null=True)),
                ('par_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('rights_restrictions', models.TextField(blank=True, help_text='Rights, privileges, restrictions and conditions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_classes', to='clients.client')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('client', 'name')},
            },
        ),
    ]
