# Generated by Django 5.2.15 on 2026-06-12 20:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0043_aiextraction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('partner', 'Partner'), ('associate', 'Associate'), ('paralegal', 'Paralegal'), ('clerk', 'Corporate Clerk'), ('accountant', 'Accountant'), ('admin', 'Admin')], max_length=30)),
                ('category', models.CharField(blank=True, choices=[('incorporation', 'Incorporation'), ('annual_maintenance', 'Annual Maintenance'), ('compliance', 'Compliance Filing'), ('document_drafting', 'Document Drafting'), ('minute_book', 'Minute Book Work'), ('consultation', 'Consultation'), ('tax_filing', 'Tax Filing'), ('ubo', 'UBO/KYC'), ('registered_agent', 'Registered Agent'), ('other', 'Other')], max_length=50)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_default', models.BooleanField(default=False, help_text='Fallback rate when no other match')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Billing Rate',
                'verbose_name_plural': 'Billing Rates',
                'ordering': ['firm', 'role', 'category'],
            },
        ),
        migrations.CreateModel(
            name='CollectionsRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_day_1', models.PositiveIntegerField(default=1)),
                ('reminder_day_2', models.PositiveIntegerField(default=7)),
                ('reminder_day_3', models.PositiveIntegerField(default=14)),
                ('reminder_day_final', models.PositiveIntegerField(default=30)),
                ('auto_mark_overdue', models.BooleanField(default=True, help_text='Auto-mark invoices as overdue past due date')),
                ('send_client_emails', models.BooleanField(default=True)),
                ('auto_escalate_to_firm', models.BooleanField(default=True, help_text='Notify firm after final reminder')),
                ('suspend_services_after_days', models.PositiveIntegerField(default=0, help_text='0 = never suspend')),
                ('reminder_email_subject', models.CharField(default='Payment reminder — {{ firm_name }}', max_length=200)),
                ('reminder_email_body', models.TextField(default='Dear {{ client_name }},\n\nThis is a reminder that invoice {{ invoice_number }} for ${{ amount }} was due on {{ due_date }} and remains unpaid.\n\nYou can pay online here: {{ payment_link }}\n\nIf payment has already been made, please disregard this notice.\n\nThank you,\n{{ firm_name }}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntitySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('trialing', 'Trialing'), ('paused', 'Paused')], default='active', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='annual', max_length=20)),
                ('current_period_start', models.DateField(blank=True, null=True)),
                ('current_period_end', models.DateField(blank=True, null=True)),
                ('next_billing_date', models.DateField(blank=True, null=True)),
                ('trial_end_date', models.DateField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('custom_price_override', models.PositiveIntegerField(blank=True, help_text='Override price in cents', null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('auto_renew', models.BooleanField(default=True)),
                ('services_included', models.JSONField(blank=True, default=dict, help_text='Custom service overrides per entity')),
                ('notes', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entity Subscription',
                'verbose_name_plural': 'Entity Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('cash', 'Cash'), ('other', 'Other')], default='stripe', max_length=20)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, help_text='Check #, Stripe ID, etc.', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100)),
                ('stripe_receipt_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('amount_charged', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=100)),
                ('stripe_invoice_url', models.URLField(blank=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='standard', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price_monthly', models.PositiveIntegerField(default=0, help_text='Price in cents')),
                ('price_quarterly', models.PositiveIntegerField(default=0, help_text='Price in cents')),
                ('price_annual', models.PositiveIntegerField(default=0, help_text='Price in cents')),
                ('includes_compliance_monitoring', models.BooleanField(default=True)),
                ('includes_document_generation', models.BooleanField(default=False, help_text='Auto-generate annual resolutions, minutes')),
                ('includes_annual_return_filing', models.BooleanField(default=False)),
                ('includes_registered_agent', models.BooleanField(default=False)),
                ('includes_ubo_monitoring', models.BooleanField(default=False, help_text='Beneficial ownership monitoring')),
                ('includes_ai_drafting', models.BooleanField(default=False, help_text='AI-powered document drafting')),
                ('includes_api_access', models.BooleanField(default=False)),
                ('max_documents_per_month', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('max_entities', models.PositiveIntegerField(default=1, help_text='Max entities covered by this plan')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='#2563eb', help_text='Hex color for UI badge', max_length=7)),
                ('icon', models.CharField(default='building', help_text='Icon name for UI', max_length=50)),
                ('stripe_price_id_monthly', models.CharField(blank=True, help_text='Stripe Price ID for monthly billing', max_length=100)),
                ('stripe_price_id_annual', models.CharField(blank=True, help_text='Stripe Price ID for annual billing', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['sort_order', 'tier'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Description of work performed')),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated: hours × rate', max_digits=10)),
                ('category', models.CharField(choices=[('incorporation', 'Incorporation'), ('annual_maintenance', 'Annual Maintenance'), ('compliance', 'Compliance Filing'), ('document_drafting', 'Document Drafting'), ('minute_book', 'Minute Book Work'), ('consultation', 'Consultation'), ('tax_filing', 'Tax Filing'), ('ubo', 'UBO/KYC'), ('registered_agent', 'Registered Agent'), ('other', 'Other')], default='general', max_length=50)),
                ('billing_status', models.CharField(choices=[('unbilled', 'Unbilled'), ('billed', 'Billed'), ('non_billable', 'Non-Billable'), ('written_off', 'Written Off')], default='unbilled', max_length=20)),
                ('auto_generated', models.BooleanField(default=False, help_text='Generated from platform activity')),
                ('client_narrative', models.TextField(blank=True, help_text='Client-ready description for invoice')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Time Entry',
                'verbose_name_plural': 'Time Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnbilledActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('document_generated', 'Document Generated'), ('document_edited', 'Document Edited'), ('compliance_task_completed', 'Compliance Task Completed'), ('email_sent', 'Email Sent to Client'), ('filing_submitted', 'Filing Submitted'), ('call_logged', 'Call Logged'), ('meeting_held', 'Meeting Held'), ('review_completed', 'Review Completed'), ('template_filled', 'Template Filled'), ('ai_draft_performed', 'AI Draft Performed')], max_length=30)),
                ('description', models.TextField()),
                ('occurred_at', models.DateTimeField()),
                ('estimated_minutes', models.PositiveIntegerField(default=0)),
                ('suggested_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_converted', models.BooleanField(default=False, help_text='Converted to TimeEntry')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Unbilled Activity',
                'verbose_name_plural': 'Unbilled Activities',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='auto_generated',
            field=models.BooleanField(default=False, help_text='Generated by system (e.g., subscription billing)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='next_reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reminder_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of payment reminders sent'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, help_text='Stripe Invoice ID', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stripe_payment_link',
            field=models.URLField(blank=True, help_text='Stripe-hosted payment link'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stripe_payment_link_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='HST/GST collected', max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='service_type',
            field=models.CharField(choices=[('bookkeeping', 'Bookkeeping'), ('tax_return', 'Tax Return'), ('incorporation', 'Incorporation'), ('annual_maintenance', 'Annual Maintenance'), ('registered_agent', 'Registered Agent'), ('consultation', 'Consultation'), ('document_drafting', 'Document Drafting'), ('compliance_filing', 'Compliance Filing'), ('minute_book', 'Minute Book'), ('ubo_kyc', 'UBO/KYC'), ('hst_filing', 'HST/GST Filing'), ('payroll', 'Payroll'), ('subscription', 'Entity Subscription'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('void', 'Void'), ('refunded', 'Refunded')], default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_date'], name='clients_inv_status_e27c98_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['stripe_invoice_id'], name='clients_inv_stripe__0cc6c0_idx'),
        ),
        migrations.AddField(
            model_name='billingrate',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_rates', to='clients.firm'),
        ),
        migrations.AddField(
            model_name='billingrate',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User-specific rate override', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_rates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collectionsrule',
            name='firm',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collections_rules', to='clients.firm'),
        ),
        migrations.AddField(
            model_name='entitysubscription',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='clients.client'),
        ),
        migrations.AddField(
            model_name='entitysubscription',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_subscriptions', to='clients.firm'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='clients.invoice'),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_invoice', to='clients.invoice'),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_invoices', to='clients.entitysubscription'),
        ),
        migrations.AddField(
            model_name='entitysubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='clients.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='clients.client'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Invoice this entry was billed on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='clients.invoice'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unbilledactivity',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unbilled_activities', to='clients.client'),
        ),
        migrations.AddField(
            model_name='unbilledactivity',
            name='converted_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_activity', to='clients.timeentry'),
        ),
        migrations.AddField(
            model_name='unbilledactivity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='billingrate',
            index=models.Index(fields=['firm', 'role'], name='clients_bil_firm_id_06fc65_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['invoice', 'payment_date'], name='clients_pay_invoice_621893_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioninvoice',
            index=models.Index(fields=['subscription', 'is_paid'], name='clients_sub_subscri_14497b_idx'),
        ),
        migrations.AddIndex(
            model_name='entitysubscription',
            index=models.Index(fields=['client', 'status'], name='clients_ent_client__8bf43d_idx'),
        ),
        migrations.AddIndex(
            model_name='entitysubscription',
            index=models.Index(fields=['firm', 'status'], name='clients_ent_firm_id_3355d5_idx'),
        ),
        migrations.AddIndex(
            model_name='entitysubscription',
            index=models.Index(fields=['next_billing_date'], name='clients_ent_next_bi_affc32_idx'),
        ),
        migrations.AddIndex(
            model_name='entitysubscription',
            index=models.Index(fields=['status', 'next_billing_date'], name='clients_ent_status_fb7daa_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['client', 'billing_status'], name='clients_tim_client__b0b725_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['user', 'date'], name='clients_tim_user_id_342aa3_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['billing_status', 'date'], name='clients_tim_billing_fae9fb_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['invoice'], name='clients_tim_invoice_181c69_idx'),
        ),
        migrations.AddIndex(
            model_name='unbilledactivity',
            index=models.Index(fields=['client', 'is_converted'], name='clients_unb_client__6fe7fc_idx'),
        ),
        migrations.AddIndex(
            model_name='unbilledactivity',
            index=models.Index(fields=['user', 'is_converted'], name='clients_unb_user_id_ae7c97_idx'),
        ),
    ]
