# Generated by Django 5.2.15 on 2026-06-12 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0044_entity_subscriptions_and_billing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncorporationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_name_1', models.CharField(blank=True, help_text='First choice name', max_length=255)),
                ('proposed_name_2', models.CharField(blank=True, help_text='Second choice name', max_length=255)),
                ('proposed_name_3', models.CharField(blank=True, help_text='Third choice name', max_length=255)),
                ('is_numbered', models.BooleanField(default=False, help_text='Use numbered company instead of named')),
                ('jurisdiction', models.CharField(choices=[('federal', 'Federal (CBCA)'), ('ontario', 'Ontario (OBCA)'), ('bc', 'British Columbia (BCBCA)'), ('alberta', 'Alberta (ABCA)'), ('quebec', 'Quebec (QBCA)'), ('nova_scotia', 'Nova Scotia'), ('manitoba', 'Manitoba'), ('saskatchewan', 'Saskatchewan'), ('new_brunswick', 'New Brunswick'), ('pei', 'PEI'), ('newfoundland', 'Newfoundland & Labrador'), ('nunavut', 'Nunavut'), ('nwt', 'Northwest Territories'), ('yukon', 'Yukon')], default='federal', max_length=30)),
                ('structure_type', models.CharField(choices=[('named', 'Named Share Corporation'), ('numbered', 'Numbered Corporation'), ('professional', 'Professional Corporation'), ('nonprofit', 'Non-Profit / Charity'), ('unlimited', 'Unlimited Liability Company')], default='named', max_length=20)),
                ('registered_address', models.TextField(blank=True)),
                ('mailing_address', models.TextField(blank=True)),
                ('business_activity', models.TextField(blank=True, help_text='Description of business activity')),
                ('authorized_shares', models.TextField(blank=True, help_text='e.g., "Unlimited Common shares without par value"')),
                ('has_multiple_share_classes', models.BooleanField(default=False)),
                ('share_class_details', models.TextField(blank=True)),
                ('min_directors', models.PositiveIntegerField(default=1)),
                ('max_directors', models.PositiveIntegerField(default=10)),
                ('fiscal_year_end', models.CharField(default='December 31', max_length=20)),
                ('current_step', models.CharField(choices=[('draft', 'Draft'), ('name_search', 'Name Search'), ('nuans', 'NUANS Report'), ('articles', 'Articles of Incorporation'), ('bylaws', 'Organizational By-laws'), ('org_resolutions', 'Organizational Resolutions'), ('cra_bn', 'CRA Business Number'), ('gst_hst', 'GST/HST Registration'), ('payroll', 'Payroll Registration'), ('banking', 'Banking Package'), ('minute_book', 'Minute Book Assembly'), ('welcome_package', 'Welcome Package'), ('complete', 'Complete'), ('on_hold', 'On Hold')], default='draft', max_length=30)),
                ('steps_completed', models.JSONField(blank=True, default=list)),
                ('steps_pending', models.JSONField(blank=True, default=list)),
                ('total_steps', models.PositiveIntegerField(default=10)),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed incorporation fee', max_digits=10)),
                ('disbursements', models.DecimalField(decimal_places=2, default=0.0, help_text='Government filing fees etc.', max_digits=10)),
                ('invoice_generated', models.BooleanField(default=False)),
                ('documents_generated', models.JSONField(blank=True, default=list, help_text='List of document IDs/names generated')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incorporation_projects', to='clients.client')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_incorporations', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incorporation_projects', to='clients.firm')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incorporation_project', to='clients.invoice')),
            ],
            options={
                'verbose_name': 'Incorporation Project',
                'verbose_name_plural': 'Incorporation Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncorporationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_key', models.CharField(max_length=50)),
                ('step_name', models.CharField(max_length=255)),
                ('step_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('checklist_items', models.JSONField(blank=True, default=list)),
                ('generated_documents', models.JSONField(blank=True, default=list)),
                ('external_reference', models.CharField(blank=True, help_text='NUANS order #, CRA confirmation #, etc.', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='clients.incorporationproject')),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
        migrations.AddIndex(
            model_name='incorporationproject',
            index=models.Index(fields=['client', 'current_step'], name='clients_inc_client__b6c186_idx'),
        ),
        migrations.AddIndex(
            model_name='incorporationproject',
            index=models.Index(fields=['firm', 'current_step'], name='clients_inc_firm_id_fac380_idx'),
        ),
        migrations.AddIndex(
            model_name='incorporationproject',
            index=models.Index(fields=['jurisdiction'], name='clients_inc_jurisdi_bc06de_idx'),
        ),
        migrations.AddIndex(
            model_name='incorporationstep',
            index=models.Index(fields=['project', 'status'], name='clients_inc_project_45cced_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='incorporationstep',
            unique_together={('project', 'step_key')},
        ),
    ]
