# Generated by Django 5.2.15 on 2026-06-12 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0050_intake_form'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAuthnChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.CharField(max_length=512, unique=True)),
                ('challenge_type', models.CharField(choices=[('registration', 'Registration'), ('authentication', 'Authentication')], max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('rp_id', models.CharField(default='mortacc.com', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WebAuthn Challenge',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebAuthnCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.CharField(help_text='Base64-encoded credential ID', max_length=512, unique=True)),
                ('public_key', models.TextField(help_text='COSE-encoded public key')),
                ('sign_count', models.PositiveIntegerField(default=0, help_text='Signature counter for replay protection')),
                ('device_name', models.CharField(blank=True, help_text='e.g., "iPhone 15 Pro", "Windows Hello", "YubiKey 5"', max_length=255)),
                ('device_type', models.CharField(blank=True, help_text='platform (FaceID/TouchID/Hello) or cross-platform (security key)', max_length=50)),
                ('aaguid', models.CharField(blank=True, help_text='Authenticator Attestation GUID', max_length=64)),
                ('transports', models.JSONField(blank=True, default=list, help_text='Supported transports: ["internal","usb","nfc","ble"]')),
                ('backup_eligible', models.BooleanField(default=False)),
                ('backup_state', models.BooleanField(default=False)),
                ('uv_initialized', models.BooleanField(default=True, help_text='User verification supported')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WebAuthn Credential',
                'verbose_name_plural': 'WebAuthn Credentials',
                'ordering': ['-last_used_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BiometricSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_sessions', to=settings.AUTH_USER_MODEL)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.webauthncredential')),
            ],
            options={
                'verbose_name': 'Biometric Session',
                'verbose_name_plural': 'Biometric Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
