# Generated by Django 5.2.15 on 2026-06-12 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0053_portal_notifications_analytics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('articles_amalgamation', 'Articles of Amalgamation'), ('articles_continuance', 'Articles of Continuance'), ('articles_dissolution', 'Articles of Dissolution'), ('articles_revival', 'Articles of Revival'), ('articles_amendment', 'Articles of Amendment'), ('estate_freeze', 'Estate Freeze Package'), ('butterfly', 'Butterfly Transaction Documents'), ('section85_rollover', 'Section 85 Rollover Agreement'), ('section86_exchange', 'Section 86 Share Exchange'), ('asset_purchase', 'Asset Purchase Agreement'), ('share_purchase', 'Share Purchase Agreement'), ('amalgamation_agreement', 'Amalgamation Agreement'), ('unanimous_sha', 'Unanimous Shareholder Agreement'), ('limited_partnership', 'Limited Partnership Agreement'), ('joint_venture', 'Joint Venture Agreement'), ('voting_trust', 'Voting Trust Agreement'), ('t2057_election', 'T2057 Election Form'), ('t2058_election', 'T2058 Election Form'), ('capital_dividend_election', 'Capital Dividend Election'), ('professional_corp', 'Professional Corporation Setup Package'), ('not_for_profit', 'Not-For-Profit Incorporation Package'), ('offshore_setup', 'Offshore/International Structure')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('reviewed', 'Reviewed'), ('final', 'Final'), ('signed', 'Signed')], default='draft', max_length=20)),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Variables for template population')),
                ('generated_content', models.TextField(blank=True)),
                ('generation_prompt', models.TextField(blank=True)),
                ('ai_model', models.CharField(default='claude', max_length=50)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='ai_documents/')),
                ('word_file', models.FileField(blank=True, null=True, upload_to='ai_documents/')),
                ('document_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_documents', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_documents', to='clients.firm')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.invoice')),
            ],
            options={
                'verbose_name': 'AI Document',
                'verbose_name_plural': 'AI Documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'document_type'], name='clients_aid_client__37059f_idx'), models.Index(fields=['firm', 'status'], name='clients_aid_firm_id_aa245b_idx')],
            },
        ),
    ]
