# Generated by Django 5.2.15 on 2026-06-14 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0055_rbac_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ESignatureEnvelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of this signature package', max_length=255)),
                ('message', models.TextField(blank=True, help_text='Message to all signers')),
                ('document_file', models.FileField(help_text='The document to be signed', upload_to='e_signatures/')),
                ('document_name', models.CharField(help_text='Display name of the document', max_length=255)),
                ('signing_order', models.CharField(choices=[('sequential', 'Sequential — signers sign one after another'), ('parallel', 'Parallel — all signers can sign at any time')], default='sequential', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('partially_signed', 'Partially Signed'), ('completed', 'Completed'), ('declined', 'Declined'), ('expired', 'Expired'), ('voided', 'Voided')], default='draft', max_length=20)),
                ('require_signer_name', models.BooleanField(default=True, help_text='Require signers to type their full name')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_envelopes', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_envelopes', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_envelopes', to='clients.firm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ESignatureSigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('order', models.PositiveIntegerField(default=0, help_text='Signing order (0 = first)')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('signed', 'Signed'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('signed_name', models.CharField(blank=True, help_text='Name typed by signer at signing', max_length=255)),
                ('signed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent at signing')),
                ('decline_reason', models.TextField(blank=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='clients.esignatureenvelope')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ESignatureEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Envelope Created'), ('sent', 'Sent to Signers'), ('viewed', 'Document Viewed'), ('signed', 'Document Signed'), ('completed', 'All Signatures Completed'), ('declined', 'Signature Declined'), ('reminded', 'Reminder Sent'), ('expired', 'Envelope Expired'), ('voided', 'Envelope Voided')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='clients.esignatureenvelope')),
                ('signer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='clients.esignaturesigner')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='esignatureenvelope',
            index=models.Index(fields=['firm', '-created_at'], name='clients_esi_firm_id_9ec7b9_idx'),
        ),
        migrations.AddIndex(
            model_name='esignatureenvelope',
            index=models.Index(fields=['client', '-created_at'], name='clients_esi_client__5c9970_idx'),
        ),
        migrations.AddIndex(
            model_name='esignatureenvelope',
            index=models.Index(fields=['status'], name='clients_esi_status_275ffc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='esignaturesigner',
            unique_together={('envelope', 'email')},
        ),
    ]
