# Generated by Django 5.2.15 on 2026-06-14 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0056_e_signature_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='T2Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.PositiveIntegerField(help_text='Tax year (e.g. 2025 for the 2025 tax year)')),
                ('fiscal_year_start', models.DateField()),
                ('fiscal_year_end', models.DateField()),
                ('net_income_per_books', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('depreciation_addback', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('meals_entertainment_addback', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('golf_club_addback', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('penalties_addback', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('life_insurance_addback', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('political_donations_addback', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_addbacks', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cca_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('capital_gains_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_income_for_tax', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cca_class_1', models.DecimalField(decimal_places=2, default=0, help_text='Buildings (4% declining)', max_digits=12)),
                ('cca_class_8', models.DecimalField(decimal_places=2, default=0, help_text='Furniture & Equipment (20%)', max_digits=12)),
                ('cca_class_10', models.DecimalField(decimal_places=2, default=0, help_text='Vehicles (30%)', max_digits=12)),
                ('cca_class_50', models.DecimalField(decimal_places=2, default=0, help_text='Computers (55%)', max_digits=12)),
                ('cca_class_14', models.DecimalField(decimal_places=2, default=0, help_text='Intangible assets', max_digits=12)),
                ('total_cca_claimed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('active_business_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('investment_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('capital_gains', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('salaries_wages', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('professional_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('office_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('insurance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advertising', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interest_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('taxable_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sbd_eligible_income', models.DecimalField(decimal_places=2, default=0, help_text='Income eligible for Small Business Deduction', max_digits=12)),
                ('sbd_rate', models.DecimalField(decimal_places=4, default=0.09, help_text='SBD rate (9% federal for 2025+)', max_digits=5)),
                ('general_rate', models.DecimalField(decimal_places=4, default=0.15, help_text='General corporate rate (15% federal)', max_digits=5)),
                ('federal_tax_part1', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('provincial_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dividend_tax_credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('foreign_tax_credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('investment_tax_credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_credits', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_tax_owing', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('preparing', 'Preparing'), ('review', 'Under Review'), ('client_approval', 'Awaiting Client Approval'), ('ready_to_file', 'Ready to File'), ('filed', 'Filed with CRA'), ('accepted', 'Accepted by CRA'), ('rejected', 'Rejected / Needs Revision')], default='not_started', max_length=20)),
                ('prepared_by', models.CharField(blank=True, max_length=255)),
                ('reviewed_by', models.CharField(blank=True, max_length=255)),
                ('filing_method', models.CharField(choices=[('efile', 'CRA E-File'), ('netfile', 'NetFile'), ('paper', 'Paper')], default='efile', max_length=20)),
                ('cra_confirmation', models.CharField(blank=True, help_text='CRA confirmation number', max_length=50)),
                ('filed_date', models.DateField(blank=True, null=True)),
                ('accepted_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t2_returns', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_t2_returns', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t2_returns', to='clients.firm')),
            ],
            options={
                'ordering': ['-tax_year', '-created_at'],
                'indexes': [models.Index(fields=['firm', '-tax_year'], name='clients_t2r_firm_id_cf604d_idx'), models.Index(fields=['client', '-tax_year'], name='clients_t2r_client__b9f223_idx'), models.Index(fields=['status'], name='clients_t2r_status_309651_idx')],
                'unique_together': {('client', 'tax_year')},
            },
        ),
    ]
