# Generated by Django 5.2.15 on 2026-06-14 19:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0057_t2_return'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerJobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100)),
                ('job_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('records_affected', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('triggered_by', models.CharField(default='scheduler', max_length=50)),
            ],
            options={
                'verbose_name': 'Scheduler Job Log',
                'verbose_name_plural': 'Scheduler Job Logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['job_id', '-started_at'], name='clients_sch_job_id_ca7b5e_idx'), models.Index(fields=['status'], name='clients_sch_status_e4792c_idx')],
            },
        ),
    ]
