# Generated by Django 5.2.15 on 2026-06-14 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0058_scheduler_job_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChasingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. "2026 Annual Maintenance Documents"', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('escalated', 'Escalated to Accountant')], default='active', max_length=20)),
                ('max_reminders', models.PositiveIntegerField(default=5)),
                ('escalate_after_days', models.PositiveIntegerField(default=14)),
                ('escalate_to_email', models.EmailField(blank=True, max_length=254)),
                ('reminder_count', models.PositiveIntegerField(default=0)),
                ('last_reminder_sent', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chasing_campaigns', to='clients.client')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chasing_campaigns', to='clients.firm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChasingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('document', 'Document Upload'), ('signature', 'E-Signature'), ('form', 'Form Completion'), ('information', 'Information Request'), ('payment', 'Payment')], default='document', max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clients.chasingcampaign')),
            ],
            options={
                'ordering': ['status', 'due_date'],
            },
        ),
    ]
