# Generated by Django 5.2.15 on 2026-06-14 21:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0059_chasing_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='T1Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.PositiveIntegerField()),
                ('token', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('sent', 'Sent to Client'), ('in_progress', 'Client Working'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('complete', 'Complete')], default='not_started', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'Français')], default='en', max_length=10)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('common_law', 'Common-Law'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=30)),
                ('marital_status_changed', models.BooleanField(default=False)),
                ('address_changed', models.BooleanField(default=False)),
                ('new_address', models.TextField(blank=True)),
                ('dependants', models.PositiveIntegerField(default=0)),
                ('has_employment_income', models.BooleanField(default=False)),
                ('has_self_employment', models.BooleanField(default=False)),
                ('has_rental_income', models.BooleanField(default=False)),
                ('has_investment_income', models.BooleanField(default=False)),
                ('has_capital_gains', models.BooleanField(default=False)),
                ('has_foreign_income', models.BooleanField(default=False)),
                ('has_pension_income', models.BooleanField(default=False)),
                ('has_rrsp_deduction', models.BooleanField(default=False)),
                ('has_childcare_expenses', models.BooleanField(default=False)),
                ('has_medical_expenses', models.BooleanField(default=False)),
                ('has_donations', models.BooleanField(default=False)),
                ('has_tuition', models.BooleanField(default=False)),
                ('has_student_loan_interest', models.BooleanField(default=False)),
                ('has_moving_expenses', models.BooleanField(default=False)),
                ('has_union_dues', models.BooleanField(default=False)),
                ('has_rent_receipts', models.BooleanField(default=False)),
                ('has_property_tax', models.BooleanField(default=False)),
                ('completion_pct', models.PositiveIntegerField(default=0)),
                ('risk_flags', models.JSONField(default=list)),
                ('ai_summary', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t1_organizers', to='clients.client')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t1_organizers', to='clients.firm')),
            ],
            options={
                'ordering': ['-tax_year', '-created_at'],
                'unique_together': {('client', 'tax_year')},
            },
        ),
        migrations.CreateModel(
            name='T1Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('t4', 'T4 — Employment Income'), ('t4a', 'T4A — Pension/Other Income'), ('t5', 'T5 — Investment Income'), ('t3', 'T3 — Trust Income'), ('t2202', 'T2202 — Tuition Certificate'), ('rrsp', 'RRSP Contribution Receipt'), ('t4e', 'T4E — EI Benefits'), ('t5007', 'T5007 — Social Assistance'), ('rc62', 'RC62 — Universal Child Care Benefit'), ('medical', 'Medical Expense Receipts'), ('childcare', 'Childcare Expense Receipts'), ('donation', 'Charitable Donation Receipts'), ('rent', 'Rent Receipts'), ('property_tax', 'Property Tax Receipts'), ('capital_gains', 'Capital Gains — Disposition Statements'), ('foreign_income', 'Foreign Income Documents'), ('self_employment', 'Self-Employment — Income & Expenses'), ('rental', 'Rental Income & Expenses'), ('moving', 'Moving Expense Receipts'), ('student_loan', 'Student Loan Interest Certificate'), ('union_dues', 'Union Dues Receipt'), ('other', 'Other Document')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('file', models.FileField(blank=True, null=True, upload_to='t1_documents/')),
                ('status', models.CharField(choices=[('missing', 'Missing'), ('uploaded', 'Uploaded'), ('not_applicable', 'Not Applicable'), ('needs_review', 'Needs Review')], default='missing', max_length=20)),
                ('original_filename', models.CharField(blank=True, max_length=500)),
                ('renamed_filename', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.t1organizer')),
            ],
            options={
                'ordering': ['doc_type'],
            },
        ),
    ]
