# Generated by Django 5.2.15 on 2026-06-14 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0060_t1_organizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRAAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('gst_hst', 'GST/HST Account'), ('payroll', 'Payroll / Source Deductions'), ('corporate_tax', 'Corporate Tax Account'), ('qst', 'QST Account (Revenu Québec)')], max_length=20)),
                ('account_number', models.CharField(blank=True, help_text='CRA business number + account suffix', max_length=30)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, help_text='Positive = owing, negative = credit', max_digits=12)),
                ('last_known_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_as_of', models.DateField(blank=True, null=True)),
                ('next_filing_due', models.DateField(blank=True, null=True)),
                ('last_filed_date', models.DateField(blank=True, null=True)),
                ('filing_status', models.CharField(choices=[('unknown', 'Unknown'), ('up_to_date', 'Up to Date'), ('due_soon', 'Due Soon'), ('overdue', 'Overdue'), ('filed', 'Filed')], default='unknown', max_length=20)),
                ('installments_required', models.BooleanField(default=False)),
                ('next_installment_date', models.DateField(blank=True, null=True)),
                ('next_installment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('sync_method', models.CharField(choices=[('manual', 'Manual Entry'), ('api', 'CRA API'), ('estimated', 'Estimated from filings')], default='manual', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cra_accounts', to='clients.client')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cra_accounts', to='clients.firm')),
            ],
            options={
                'ordering': ['account_type'],
                'unique_together': {('client', 'account_type')},
            },
        ),
    ]
