# Generated by Django 5.2.15 on 2026-06-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0061_cra_connector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='starter', max_length=20),
        ),
    ]
