# Generated by Django 5.2.15 on 2026-06-18 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0062_alter_userprofile_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.CharField(db_index=True, help_text='Matches the module id in academy_modules.json', max_length=100)),
                ('chapter_id', models.CharField(blank=True, default='', help_text='Matches the chapter id. Blank = module-level progress.', max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('quiz_score', models.FloatField(blank=True, help_text='0–100', null=True)),
                ('quiz_passed', models.BooleanField(default=False)),
                ('quiz_answers', models.JSONField(blank=True, default=dict, help_text='Stores user answers keyed by question index')),
                ('current_chapter_index', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Academy Progress',
                'verbose_name_plural': 'Academy Progress',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'module_id'], name='clients_aca_user_id_5367cf_idx')],
                'unique_together': {('user', 'module_id', 'chapter_id')},
            },
        ),
    ]
