# Generated by Django 5.2.15 on 2026-06-20 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0064_add_beauty_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='beautyprovider',
            name='instagram',
            field=models.URLField(blank=True, help_text='Instagram profile URL'),
        ),
        migrations.AddField(
            model_name='beautyprovider',
            name='tiktok',
            field=models.URLField(blank=True, help_text='TikTok profile URL'),
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='e.g., "Lead Injector", "Master Stylist"', max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='providers/staff/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='clients.beautyprovider')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='clients.beautyprovider')),
            ],
            options={
                'ordering': ['day'],
                'unique_together': {('provider', 'day')},
            },
        ),
    ]
