# Generated by Django 5.2.15 on 2026-06-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0066_add_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='beautyprovider',
            name='facebook',
            field=models.URLField(blank=True, help_text='Facebook page URL'),
        ),
        migrations.AddField(
            model_name='beautyprovider',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp number with country code, e.g. 15145550123', max_length=20),
        ),
        migrations.AddField(
            model_name='providerphoto',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube/Vimeo embed URL'),
        ),
        migrations.AlterField(
            model_name='providerphoto',
            name='image',
            field=models.ImageField(blank=True, upload_to='providers/gallery/'),
        ),
    ]
