# Generated by Django 5.2.15 on 2026-06-20 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0068_add_claim_ownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('profile_view', 'Profile View'), ('search_appearance', 'Search Appearance'), ('phone_click', 'Phone Click'), ('website_click', 'Website Click'), ('instagram_click', 'Instagram Click'), ('tiktok_click', 'TikTok Click'), ('facebook_click', 'Facebook Click'), ('whatsapp_click', 'WhatsApp Click')], db_index=True, max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='clients.beautyprovider')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'event_type', 'created_at'], name='clients_ana_provide_f36e10_idx'), models.Index(fields=['provider', 'created_at'], name='clients_ana_provide_8c3d23_idx')],
            },
        ),
    ]
