# Generated by Django 5.2.15 on 2026-06-20 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0069_add_analytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeforeAfterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_type', models.CharField(choices=[('botox', 'Botox'), ('lip_fillers', 'Lip Fillers'), ('prp', 'PRP Therapy'), ('laser_hair', 'Laser Hair Removal'), ('hair_extensions', 'Hair Extensions'), ('brows', 'Brows'), ('lashes', 'Lashes'), ('hydrafacial', 'Hydrafacial'), ('skin', 'Skin Treatments'), ('microneedling', 'Microneedling'), ('chemical_peel', 'Chemical Peel'), ('other', 'Other')], db_index=True, max_length=30)),
                ('before_photo', models.ImageField(blank=True, upload_to='results/before/')),
                ('after_photo', models.ImageField(blank=True, upload_to='results/after/')),
                ('description', models.TextField(blank=True, help_text='Optional notes about the result')),
                ('date', models.DateField(blank=True, help_text='Date of the procedure/result', null=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='before_after_results', to='clients.beautyprovider')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['procedure_type', 'is_published'], name='clients_bef_procedu_e470c2_idx'), models.Index(fields=['city', 'is_published'], name='clients_bef_city_0d7bf7_idx'), models.Index(fields=['provider', 'is_published'], name='clients_bef_provide_42f66b_idx')],
            },
        ),
    ]
