# Generated by Django 5.2.15 on 2026-06-20 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0071_add_business_import_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_photo', models.ImageField(blank=True, upload_to='portfolio/')),
                ('after_photo', models.ImageField(blank=True, upload_to='portfolio/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo/Instagram reel URL')),
                ('description', models.TextField(blank=True)),
                ('procedure_type', models.CharField(blank=True, choices=[('botox', 'Botox'), ('lip_fillers', 'Lip Fillers'), ('prp', 'PRP Therapy'), ('laser_hair', 'Laser Hair Removal'), ('hair_extensions', 'Hair Extensions'), ('brows', 'Brows'), ('lashes', 'Lashes'), ('hydrafacial', 'Hydrafacial'), ('skin', 'Skin Treatments'), ('microneedling', 'Microneedling'), ('chemical_peel', 'Chemical Peel'), ('other', 'Other')], max_length=30)),
                ('products_used', models.CharField(blank=True, help_text='e.g., Juvederm Ultra, Botox 50u', max_length=300)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_posts', to='clients.beautyprovider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_likes', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='clients.portfoliopost')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='clients.portfoliopost')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_saves', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='clients.beautyprovider')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='portfoliopost',
            index=models.Index(fields=['provider', '-created_at'], name='clients_por_provide_77e3df_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliopost',
            index=models.Index(fields=['procedure_type', 'is_published'], name='clients_por_procedu_77a9f7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portfoliolike',
            unique_together={('post', 'session_key'), ('post', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='portfoliosave',
            unique_together={('post', 'session_key'), ('post', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='providerfollow',
            unique_together={('provider', 'session_key'), ('provider', 'user')},
        ),
    ]
