# Generated by Django 5.2.15 on 2026-06-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0072_add_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='beautyprovider',
            name='plan',
            field=models.CharField(choices=[('free', 'Free Listing'), ('premium', 'Premium Listing'), ('featured', 'Featured Listing')], db_index=True, default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='beautyprovider',
            name='plan_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beautyprovider',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
