# Generated by Django 5.2.15 on 2026-06-20 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0073_add_provider_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('business_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, choices=[('medical_aesthetics', 'Medical Aesthetics'), ('hair', 'Hair'), ('beauty', 'Beauty'), ('wellness', 'Wellness'), ('dental_aesthetics', 'Dental Aesthetics')], max_length=30)),
                ('referral_code', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_converted', models.BooleanField(default=False, help_text='Converted to a real provider')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='beautyprovider',
            name='is_early_adopter',
            field=models.BooleanField(default=False, help_text='Joined in the first 100 providers'),
        ),
        migrations.AddField(
            model_name='beautyprovider',
            name='is_founding_member',
            field=models.BooleanField(default=False, help_text='Featured founding member badge'),
        ),
        migrations.AddField(
            model_name='beautyprovider',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beautyprovider',
            name='referral_code',
            field=models.CharField(blank=True, help_text='Unique referral code for provider referral program', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='beautyprovider',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='clients.beautyprovider'),
        ),
    ]
