# Generated by Django 5.2.15 on 2026-06-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0074_add_launch_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='beautyprovider',
            name='is_mortea_recommended',
            field=models.BooleanField(default=False, help_text='Mortea Recommended — meets all verification criteria'),
        ),
        migrations.AddField(
            model_name='beautyprovider',
            name='is_premium_partner',
            field=models.BooleanField(default=False, help_text='Premium Partner — premium plan + verified'),
        ),
        migrations.AddField(
            model_name='beautyprovider',
            name='is_top_rated',
            field=models.BooleanField(default=False, help_text='Top Rated badge — 4.5+ rating with 10+ reviews'),
        ),
        migrations.AddField(
            model_name='beautyprovider',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='Verified Business badge — meets quality criteria'),
        ),
        migrations.AddField(
            model_name='beautyprovider',
            name='verification_score',
            field=models.PositiveIntegerField(default=0, help_text='0-5 score based on profile completeness'),
        ),
        migrations.AddField(
            model_name='beautyprovider',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
