# Generated by Django 5.2.15 on 2026-06-20 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0075_add_verification_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeautyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('botox', 'Botox'), ('lip_fillers', 'Lip Fillers'), ('prp', 'PRP Therapy'), ('laser_hair', 'Laser Hair Removal'), ('hair_extensions', 'Hair Extensions'), ('brows', 'Brows'), ('lashes', 'Lash Extensions'), ('hydrafacial', 'Hydrafacial'), ('skin', 'Skin Treatments'), ('microneedling', 'Microneedling'), ('chemical_peel', 'Chemical Peel'), ('head_spa', 'Head Spa'), ('hair_salon', 'Hair Salon'), ('nails', 'Nails'), ('makeup', 'Makeup'), ('other', 'Other')], max_length=30)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('budget', models.CharField(blank=True, help_text='e.g., Under $200, $200-500, $500+', max_length=20)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open — Accepting Quotes'), ('closed', 'Closed — Offer Accepted'), ('expired', 'Expired')], db_index=True, default='open', max_length=20)),
                ('quote_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_estimate', models.CharField(blank=True, help_text='e.g., $350-450', max_length=100)),
                ('availability', models.CharField(blank=True, help_text='e.g., Available weekdays, next opening June 25', max_length=200)),
                ('message', models.TextField(blank=True)),
                ('portfolio_links', models.TextField(blank=True, help_text='Links to relevant portfolio posts, one per line')),
                ('status', models.CharField(choices=[('sent', 'Quote Sent'), ('viewed', 'Viewed by Client'), ('accepted', 'Accepted'), ('declined', 'Declined')], db_index=True, default='sent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='clients.beautyprovider')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='clients.beautyrequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('request', 'provider')},
            },
        ),
        migrations.AddField(
            model_name='beautyrequest',
            name='accepted_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_for', to='clients.providerquote'),
        ),
    ]
