# Generated by Django 5.2.15 on 2026-06-20 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0076_add_beauty_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='e.g., VIP, Botox, Referral', max_length=200)),
                ('total_visits', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_visit', models.DateField(blank=True, null=True)),
                ('next_appointment', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_clients', to='clients.beautyprovider')),
            ],
            options={
                'ordering': ['-last_visit', '-created_at'],
                'unique_together': {('provider', 'email')},
            },
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_type', models.CharField(choices=[('email', 'Email Campaign'), ('sms', 'SMS Reminder'), ('promotion', 'Promotion'), ('birthday', 'Birthday Offer'), ('rebooking', 'Rebooking Reminder')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='clients.beautyprovider')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('products_used', models.CharField(blank=True, max_length=300)),
                ('before_photo', models.ImageField(blank=True, upload_to='crm/treatments/')),
                ('after_photo', models.ImageField(blank=True, upload_to='crm/treatments/')),
                ('consent_signed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='clients.clientprofile')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_notes', to='clients.beautyprovider')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
