# Generated by Django 5.2.15 on 2026-06-21 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0079_add_trust_safety'),
    ]

    operations = [
        migrations.AddField(
            model_name='beautyprovider',
            name='stripe_account_id',
            field=models.CharField(blank=True, help_text='Stripe Connect account ID for receiving payouts', max_length=100),
        ),
        migrations.AddField(
            model_name='beautyprovider',
            name='stripe_onboarding_complete',
            field=models.BooleanField(default=False, help_text='Provider completed Stripe Connect onboarding'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100)),
                ('stripe_session_id', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total charged to customer', max_digits=10)),
                ('application_fee', models.DecimalField(decimal_places=2, help_text='Mortea commission', max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Amount after commission (to provider)', max_digits=10)),
                ('currency', models.CharField(default='cad', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], db_index=True, default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='clients.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total payout amount', max_digits=10)),
                ('period_start', models.DateField(help_text='Start of payout period')),
                ('period_end', models.DateField(help_text='End of payout period')),
                ('stripe_payout_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='clients.beautyprovider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
