from django.db import models
from django.utils import timezone
from .client import Client
from .leads import CorporateLead


class Invoice(models.Model):
    SERVICE_CHOICES = [
        ("bookkeeping", "Bookkeeping"),
        ("tax_return", "Tax Return"),
        ("incorporation", "Incorporation"),
        ("annual_maintenance", "Annual Maintenance"),
        ("registered_agent", "Registered Agent"),
        ("consultation", "Consultation"),
        ("document_drafting", "Document Drafting"),
        ("compliance_filing", "Compliance Filing"),
        ("minute_book", "Minute Book"),
        ("ubo_kyc", "UBO/KYC"),
        ("hst_filing", "HST/GST Filing"),
        ("payroll", "Payroll"),
        ("subscription", "Entity Subscription"),
        ("other", "Other"),
    ]

    STATUS_CHOICES = [
        ("draft", "Draft"),
        ("sent", "Sent"),
        ("paid", "Paid"),
        ("overdue", "Overdue"),
        ("void", "Void"),
        ("refunded", "Refunded"),
    ]

    client = models.ForeignKey("Client", on_delete=models.CASCADE, related_name="invoices")
    invoice_number = models.CharField(max_length=50, blank=True)
    description = models.TextField()
    service_type = models.CharField(max_length=30, choices=SERVICE_CHOICES, default="other")
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    tax_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.0, help_text='HST/GST collected')
    total_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="draft")
    invoice_date = models.DateField()
    due_date = models.DateField(null=True, blank=True)
    paid_date = models.DateField(null=True, blank=True)
    notes = models.TextField(blank=True)

    # Stripe integration
    stripe_invoice_id = models.CharField(max_length=100, blank=True, help_text='Stripe Invoice ID')
    stripe_payment_intent_id = models.CharField(max_length=100, blank=True)
    stripe_payment_link = models.URLField(blank=True, help_text='Stripe-hosted payment link')
    stripe_payment_link_id = models.CharField(max_length=100, blank=True)

    # Collections tracking
    reminder_count = models.PositiveIntegerField(default=0, help_text='Number of payment reminders sent')
    last_reminder_sent = models.DateTimeField(null=True, blank=True)
    next_reminder_date = models.DateField(null=True, blank=True)

    # Auto-generation
    auto_generated = models.BooleanField(default=False, help_text='Generated by system (e.g., subscription billing)')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-invoice_date"]
        indexes = [
            models.Index(fields=['client', 'status']),
            models.Index(fields=['status', 'due_date']),
            models.Index(fields=['stripe_invoice_id']),
        ]

    def save(self, *args, **kwargs):
        if not self.total_amount:
            self.total_amount = float(self.amount or 0) + float(self.tax_amount or 0)
        if not self.invoice_number:
            from django.db.models import Max
            max_num = Invoice.objects.aggregate(
                m=Max('invoice_number', filter=models.Q(invoice_number__startswith='INV-'))
            )['m'] or 'INV-0000'
            try:
                next_num = int(max_num.replace('INV-', '')) + 1
            except (ValueError, AttributeError):
                next_num = 1
            self.invoice_number = f'INV-{next_num:04d}'
        super().save(*args, **kwargs)

    def mark_overdue(self):
        """Mark invoice as overdue if past due date and unpaid."""
        if self.status in ('sent',) and self.due_date and self.due_date < timezone.now().date():
            self.status = 'overdue'
            self.save()

    def mark_paid(self):
        """Mark this invoice as paid."""
        self.status = 'paid'
        self.paid_date = timezone.now().date()
        self.save()
        # Fire webhook
        from .webhooks import trigger_webhook
        trigger_webhook('invoice.paid', self.client.firm, {
            'id': self.id, 'invoice_number': self.invoice_number,
            'amount': float(self.amount), 'client_id': self.client_id,
            'client_name': self.client.name, 'paid_date': str(self.paid_date),
        })

    def should_send_reminder(self):
        """Determine if a payment reminder should be sent."""
        from datetime import date, timedelta
        if self.status not in ('sent', 'overdue'):
            return False
        if not self.due_date:
            return False
        if self.last_reminder_sent and self.last_reminder_sent.date() >= date.today():
            return False
        # Send at due_date + 1, +7, +14, +30 days
        days_overdue = (date.today() - self.due_date).days
        reminder_schedule = [1, 7, 14, 30]
        next_reminder_day = None
        for d in reminder_schedule:
            if days_overdue >= d and self.reminder_count < reminder_schedule.index(d) + 1:
                next_reminder_day = d
                break
        if next_reminder_day is None:
            return False
        return True

    def __str__(self):
        return f"{self.invoice_number} — {self.client.name} — ${self.total_amount:.2f}"


class PaymentRecord(models.Model):
    """
    Record of a payment received against an invoice.
    Can be via Stripe, manual entry, or other payment method.
    """
    PAYMENT_METHODS = [
        ('stripe', 'Stripe'),
        ('bank_transfer', 'Bank Transfer'),
        ('cheque', 'Cheque'),
        ('cash', 'Cash'),
        ('other', 'Other'),
    ]

    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE, related_name='payments')
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    payment_method = models.CharField(max_length=20, choices=PAYMENT_METHODS, default='stripe')
    payment_date = models.DateField(default=timezone.now)
    reference = models.CharField(max_length=255, blank=True, help_text='Check #, Stripe ID, etc.')
    notes = models.TextField(blank=True)

    # Stripe-specific
    stripe_payment_intent_id = models.CharField(max_length=100, blank=True)
    stripe_receipt_url = models.URLField(blank=True)

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-payment_date']
        indexes = [
            models.Index(fields=['invoice', 'payment_date']),
        ]

    def __str__(self):
        return f"Payment ${self.amount:.2f} — {self.invoice.invoice_number}"


class CollectionsRule(models.Model):
    """
    Configurable collections workflow for a firm.
    Defines when and how payment reminders are sent.
    """
    firm = models.OneToOneField('Firm', on_delete=models.CASCADE, related_name='collections_rules')

    # When to send reminders (days after due date)
    reminder_day_1 = models.PositiveIntegerField(default=1)
    reminder_day_2 = models.PositiveIntegerField(default=7)
    reminder_day_3 = models.PositiveIntegerField(default=14)
    reminder_day_final = models.PositiveIntegerField(default=30)

    # Actions
    auto_mark_overdue = models.BooleanField(default=True, help_text='Auto-mark invoices as overdue past due date')
    send_client_emails = models.BooleanField(default=True)
    auto_escalate_to_firm = models.BooleanField(default=True, help_text='Notify firm after final reminder')
    suspend_services_after_days = models.PositiveIntegerField(default=0, help_text='0 = never suspend')

    # Email templates
    reminder_email_subject = models.CharField(max_length=200, default='Payment reminder — {{ firm_name }}')
    reminder_email_body = models.TextField(default=(
        'Dear {{ client_name }},\n\n'
        'This is a reminder that invoice {{ invoice_number }} for ${{ amount }} '
        'was due on {{ due_date }} and remains unpaid.\n\n'
        'You can pay online here: {{ payment_link }}\n\n'
        'If payment has already been made, please disregard this notice.\n\n'
        'Thank you,\n{{ firm_name }}'
    ))

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Collections Rules — {self.firm.name}"


class EngagementLetterRecord(models.Model):
    client = models.ForeignKey('Client', on_delete=models.CASCADE, null=True, blank=True)
    lead = models.ForeignKey('CorporateLead', on_delete=models.CASCADE, null=True, blank=True)

    full_name = models.CharField(max_length=255)
    email = models.EmailField()
    phone = models.CharField(max_length=30)

    content_html = models.TextField()
    version = models.CharField(max_length=10, default="v1")

    signed_at = models.DateTimeField(auto_now_add=True)
    is_signed = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.full_name} — {self.signed_at}"
